addons:
  apt:
    packages:
    - curl
    - tar
    - fonts-linuxlibertine

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

install:
    - source ./install_texlive.sh

script:
  - make all
