addons:
  apt:
    packages:
    - latexmk
    - texlive-fonts-extra
    - texlive-fonts-recommended
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-latex-recommended

before_install:
    - tlmgr update --self
    - tlmgr update all

script:
  - make all
